services:
  enshrouded:
    image: mornedhels/enshrouded-server:stable-proton
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15636-15637:15636-15637/udp"
    volumes:
      - ./enshrouded:/opt/enshrouded
    environment:
      - SERVER_NAME=**********
      - SERVER_PASSWORD=******
      - UPDATE_CRON=*/30 * * * *
      - PUID=4711
      - PGID=4711